version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    env_file: .env
    image: postgres
    volumes:
      # If you are using boot2docker, postgres data has to live in the VM for now until #581 is fixed
      # for more info see here: https://github.com/boot2docker/boot2docker/issues/581
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups

  debug:
    env_file: .env
    image: rhangelxs/pcdocker_debug
    command: python -c "import signal; signal.pause()"
    ports:
     - "8000:8000"
     - "2222:22"
    volumes:
     - .:/app
    depends_on:
      - postgres
    links:
     - postgres
