postgres:
  image: postgres:9.4
  volumes:
    # If you are using boot2docker, postgres data has to live in the VM for now until #581 is fixed
    # for more info see here: https://github.com/boot2docker/boot2docker/issues/581
    - /data/pcdocker/postgres:/var/lib/postgresql/data

django:
  image: rhangelxs/pcdocker_debug
  command: ./manage.py runserver 0.0.0.0:8000
  env_file: .env
  volumes:
    - .:/app
  ports:
    - "2222:22"
    - "8000:8000"
  links:
    - postgres
